deployment:
  args:
  - --registry=txt
  - --txt-prefix=external-dns-
  - --txt-owner-id=tanzu
  - --provider=rfc2136
  - --rfc2136-host=10.0.0.201
  - --rfc2136-port=53
  - --rfc2136-zone=vcf.holo.lab
  - --rfc2136-insecure
  - --rfc2136-tsig-axfr
  - --source=service
  - --source=contour-httpproxy
  - --source=ingress
  - --domain-filter=vcf.holo.lab
namespace: svc-external-dns-domain-c9
